[2024-05-11 13:56:43] [INFO    ] discord.client: logging in using static token
[2024-05-11 13:56:44] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5a29b610dc0676153cb00e859048aaa6).
[2024-05-11 13:57:50] [INFO    ] discord.client: logging in using static token
[2024-05-11 13:57:51] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c626cfbd788d3a5e91942961f9b35d6d).
[2024-05-11 13:58:03] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command px_sync cmd_tree
Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/Documents/discord_bot/NewBot/cog/Sync.py", line 38, in sync_cmd_tree
    guild_o = discord.Object(id=guild)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/.local/lib/python3.11/site-packages/discord/object.py", line 97, in __init__
    raise TypeError(f'id parameter must be convertible to int not {id.__class__.__name__}') from None
TypeError: id parameter must be convertible to int not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'cmd_tree' raised an exception: TypeError: id parameter must be convertible to int not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'cmd_tree' raised an exception: TypeError: id parameter must be convertible to int not str
[2024-05-11 14:00:23] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:00:25] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: d047a61460d3bb291cb32d688e9a62be).
[2024-05-11 14:05:18] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:05:19] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 418d2ee2ffc27bd46cbd19b66b2d63e7).
[2024-05-11 14:09:49] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:09:50] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 26882c897623db26a514a674f13809db).
[2024-05-11 14:11:51] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:11:52] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 5a676399a50facae63d343c5a0191ed6).
[2024-05-11 14:12:11] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:12:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 0b1ce66bb806b2b44a6d9ce797838fad).
[2024-05-11 14:13:28] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:13:29] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 65b4dfabdd13b625b5ccc10c9f2404f0).
[2024-05-11 14:14:29] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:14:30] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 094b8492193ab37174baf6038cfcdf48).
[2024-05-11 14:16:19] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:16:20] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 58d3b36dfa02c5c1972f26a9c9158f66).
[2024-05-11 14:17:13] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:17:14] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 067637a5f15042deca2c1edc68a57495).
[2024-05-11 14:19:43] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:19:44] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b5839921e7878bdf96897346adde199f).
[2024-05-11 14:20:28] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:20:29] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 207e727b428d59207bb5c2150d57e29b).
[2024-05-11 14:21:16] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:21:17] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 039837221fe4cccf040f9a15891dcc7a).
[2024-05-11 14:21:43] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:21:44] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2e9c904eaa06319920e8b052ca39d464).
[2024-05-11 14:23:46] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:23:47] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 14180ded4a2cc245973a888810a4eca3).
[2024-05-11 14:30:08] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:30:09] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 97e181a2284691bedfc1519fa5a8ea11).
[2024-05-11 14:41:14] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:41:15] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 9f04c42697e9b7070d52b7c4b41586dd).
[2024-05-11 14:42:29] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:42:30] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b08ba7cba8a22dfe2ebefaffa19f43db).
[2024-05-11 14:43:39] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:43:40] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 8b55b24e6aacb4496c6051186e9c5e46).
[2024-05-11 14:45:53] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:45:55] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 08162431b527814f3faa76df580e7ea0).
[2024-05-11 14:52:39] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:52:40] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a344904cb7d4d139ffe0c9183f57b31c).
[2024-05-11 14:53:42] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:53:43] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2039817b6e4b43ac41029780f6f90387).
[2024-05-11 14:54:53] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:54:54] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 3c859136c317ab07e09dc1ae930d5985).
[2024-05-11 14:58:20] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:58:21] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 69dd0dcd365593a891bba19b15739d9a).
[2024-05-11 14:59:12] [INFO    ] discord.client: logging in using static token
[2024-05-11 14:59:14] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 09795f2522286c297045722b5881bb5a).
[2024-05-11 15:00:28] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:00:29] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 017b798baffbc082b27387953a177533).
[2024-05-11 15:01:14] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:01:15] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: c833b913d8a799e8ed0a15c07968b699).
[2024-05-11 15:01:51] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:01:52] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 459943703e5a96a91ca2b679bf04a54c).
[2024-05-11 15:04:08] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:04:09] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 8572ff531deae75e996e67cef2dc6dbe).
[2024-05-11 15:04:56] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:04:58] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 25bb24dcf3d4297b1111168562ddf836).
[2024-05-11 15:05:27] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command px_date
Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/Documents/discord_bot/NewBot/cog/Date.py", line 98, in px_date
    ts = try_get_datetime(date)
         ^^^^^^^^^^^^^^^^^^^^^^
TypeError: try_get_datetime() missing 1 required positional argument: 'date_str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'px_date' raised an exception: TypeError: try_get_datetime() missing 1 required positional argument: 'date_str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 842, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'px_date' raised an exception: TypeError: try_get_datetime() missing 1 required positional argument: 'date_str'
[2024-05-11 15:06:00] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:06:01] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 0b89e7802610d5cfdcd6745b836e489d).
[2024-05-11 15:06:02] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command px_date
Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/Documents/discord_bot/NewBot/cog/Date.py", line 98, in px_date
    ts = try_get_datetime(fmt, date)
                          ^^^
NameError: name 'fmt' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'px_date' raised an exception: NameError: name 'fmt' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'px_date' raised an exception: NameError: name 'fmt' is not defined
[2024-05-11 15:06:21] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:06:22] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 21a737b907b9bc391c108a67d8e86359).
[2024-05-11 15:06:25] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command px_date
Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/Documents/discord_bot/NewBot/cog/Date.py", line 100, in px_date
    await send_message(ctx, f"{date_str} cannot be converted from {fmt_in}")
                               ^^^^^^^^
NameError: name 'date_str' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'px_date' raised an exception: NameError: name 'date_str' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'px_date' raised an exception: NameError: name 'date_str' is not defined
[2024-05-11 15:06:41] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:06:42] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: fb7988276cd52a8c51327fde461be94f).
[2024-05-11 15:07:27] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:07:29] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: e77cd355bf7547a92959240070699dc3).
[2024-05-11 15:20:06] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:20:07] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 920e0aabd3b163767ebe319960ecf8be).
[2024-05-11 15:20:55] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:20:57] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 735f33c167e1116c493d1b45207126f1).
[2024-05-11 15:22:06] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:22:07] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 2fba60e4293d354d6b4aeb0b1d8101ad).
[2024-05-11 15:27:29] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:27:30] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: a6185a2afe267974b2fccbd163e3926a).
[2024-05-11 15:29:47] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:29:48] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: b04836740a973eb90ef6a27f9a3e72b7).
[2024-05-11 15:37:51] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:37:52] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 0d1fc712322c51c33d1b87c4092b4c18).
[2024-05-11 15:39:11] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:39:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 915885de1e771e7ba2730c6403887fc1).
[2024-05-11 15:46:47] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:46:48] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: ffb39c8bfe559340cfa5b01a6a842e58).
[2024-05-11 15:48:33] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:48:34] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 86ecb9258c12d7413997d1732da1f2c5).
[2024-05-11 15:49:36] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command px_dump guild
Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/Documents/discord_bot/NewBot/cog/Dump.py", line 88, in dump_guild
    "```json\n" + json.dumps(result, indent=4) + "```"
                  ^^^^
NameError: name 'json' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'guild' raised an exception: NameError: name 'json' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pix/.local/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pix/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'guild' raised an exception: NameError: name 'json' is not defined
[2024-05-11 15:49:52] [INFO    ] discord.client: logging in using static token
[2024-05-11 15:49:53] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6b839995d4b6a4752ea7d886b62f7b0c).
[2024-05-11 16:16:10] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 6b839995d4b6a4752ea7d886b62f7b0c.
[2024-05-11 17:50:37] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session 6b839995d4b6a4752ea7d886b62f7b0c.
